notifications:
  email: false

sudo: false

language: python

cache:
  - pip

env:
  matrix:
    - REQUIREMENTS=release EXTRAS=tests

python:
  - "3.6"

matrix:
  fast_finish: true

install:
  - "travis_retry pip install -e .[$EXTRAS]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls
